//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzariaDoZe.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzariaDoZe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acessar.
        /// </summary>
        internal static string BtnAcessar_Text {
            get {
                return ResourceManager.GetString("BtnAcessar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clientes.
        /// </summary>
        internal static string BtnClientes_Text {
            get {
                return ResourceManager.GetString("BtnClientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        internal static string BtnEditar_Text {
            get {
                return ResourceManager.GetString("BtnEditar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço.
        /// </summary>
        internal static string BtnEndereco_Text {
            get {
                return ResourceManager.GetString("BtnEndereco.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string BtnExcluir_Text {
            get {
                return ResourceManager.GetString("BtnExcluir.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        internal static string BtnFechar_Text {
            get {
                return ResourceManager.GetString("BtnFechar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Funcionários.
        /// </summary>
        internal static string BtnFuncionarios_Text {
            get {
                return ResourceManager.GetString("BtnFuncionarios.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredientes.
        /// </summary>
        internal static string BtnIngredientes_Text {
            get {
                return ResourceManager.GetString("BtnIngredientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        internal static string BtnInicio_Text {
            get {
                return ResourceManager.GetString("BtnInicio.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produtos.
        /// </summary>
        internal static string BtnProdutos_Text {
            get {
                return ResourceManager.GetString("BtnProdutos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sabores.
        /// </summary>
        internal static string BtnSabores_Text {
            get {
                return ResourceManager.GetString("BtnSabores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string BtnSalvar_Text {
            get {
                return ResourceManager.GetString("BtnSalvar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string BtnSalvarIdioma_Text {
            get {
                return ResourceManager.GetString("BtnSalvarIdioma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valores das Pizzas.
        /// </summary>
        internal static string BtnValores_Text {
            get {
                return ResourceManager.GetString("BtnValores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clientes.
        /// </summary>
        internal static string clientesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("clientesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Config.
        /// </summary>
        internal static string configToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("configToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço.
        /// </summary>
        internal static string enderecoToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("enderecoToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Funcionários.
        /// </summary>
        internal static string funcionariosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("funcionariosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma/Região.
        /// </summary>
        internal static string GroupBoxIdioma_Text {
            get {
                return ResourceManager.GetString("GroupBoxIdioma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredientes.
        /// </summary>
        internal static string ingredientesToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("ingredientesToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro:.
        /// </summary>
        internal static string LabelBairro_Text {
            get {
                return ResourceManager.GetString("LabelBairro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carteira de Motorista:.
        /// </summary>
        internal static string LabelCarteiraMotorista_Text {
            get {
                return ResourceManager.GetString("LabelCarteiraMotorista.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria:.
        /// </summary>
        internal static string LabelCategoria_Text {
            get {
                return ResourceManager.GetString("LabelCategoria.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CEP:.
        /// </summary>
        internal static string LabelCEP_Text {
            get {
                return ResourceManager.GetString("LabelCEP.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade:.
        /// </summary>
        internal static string LabelCidade_Text {
            get {
                return ResourceManager.GetString("LabelCidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complemento:.
        /// </summary>
        internal static string LabelComplemento_Text {
            get {
                return ResourceManager.GetString("LabelComplemento.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF:.
        /// </summary>
        internal static string LabelCPF_Text {
            get {
                return ResourceManager.GetString("LabelCPF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail:.
        /// </summary>
        internal static string LabelEmail_Text {
            get {
                return ResourceManager.GetString("LabelEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foto:.
        /// </summary>
        internal static string LabelFoto_Text {
            get {
                return ResourceManager.GetString("LabelFoto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID:.
        /// </summary>
        internal static string LabelID_Text {
            get {
                return ResourceManager.GetString("LabelID.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma/Região.
        /// </summary>
        internal static string LabelIdioma_Text {
            get {
                return ResourceManager.GetString("LabelIdioma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredientes:.
        /// </summary>
        internal static string LabelIngredientes {
            get {
                return ResourceManager.GetString("LabelIngredientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        internal static string LabelLogin_Text {
            get {
                return ResourceManager.GetString("LabelLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro:.
        /// </summary>
        internal static string LabelLogradouro_Text {
            get {
                return ResourceManager.GetString("LabelLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matricula:.
        /// </summary>
        internal static string LabelMatricula_Text {
            get {
                return ResourceManager.GetString("LabelMatricula.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MLs:.
        /// </summary>
        internal static string LabelML_Text {
            get {
                return ResourceManager.GetString("LabelML.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome:.
        /// </summary>
        internal static string LabelNome_Text {
            get {
                return ResourceManager.GetString("LabelNome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número:.
        /// </summary>
        internal static string LabelNumero_Text {
            get {
                return ResourceManager.GetString("LabelNumero.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observações:.
        /// </summary>
        internal static string LabelObservacoes_Text {
            get {
                return ResourceManager.GetString("LabelObservacoes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a País:.
        /// </summary>
        internal static string LabelPais_Text {
            get {
                return ResourceManager.GetString("LabelPais.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha:.
        /// </summary>
        internal static string LabelSenha_Text {
            get {
                return ResourceManager.GetString("LabelSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho:.
        /// </summary>
        internal static string LabelTamanho_Text {
            get {
                return ResourceManager.GetString("LabelTamanho.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone:.
        /// </summary>
        internal static string LabelTelefone_Text {
            get {
                return ResourceManager.GetString("LabelTelefone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo:.
        /// </summary>
        internal static string LabelTipo_Text {
            get {
                return ResourceManager.GetString("LabelTipo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UF:.
        /// </summary>
        internal static string LabelUF_Text {
            get {
                return ResourceManager.GetString("LabelUF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário.
        /// </summary>
        internal static string LabelUsuario_Text {
            get {
                return ResourceManager.GetString("LabelUsuario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validade:.
        /// </summary>
        internal static string LabelValidade_Text {
            get {
                return ResourceManager.GetString("LabelValidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor:.
        /// </summary>
        internal static string LabelValor_Text {
            get {
                return ResourceManager.GetString("LabelValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor Adicional:.
        /// </summary>
        internal static string LabelValorAdc_Text {
            get {
                return ResourceManager.GetString("LabelValorAdc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produtos.
        /// </summary>
        internal static string produtosToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("produtosToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sabores.
        /// </summary>
        internal static string saboresToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("saboresToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sair.
        /// </summary>
        internal static string sairToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("sairToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma/Região.
        /// </summary>
        internal static string TabPageIdioma_Text {
            get {
                return ResourceManager.GetString("TabPageIdioma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valores das Pizzas.
        /// </summary>
        internal static string valoresDasPizzasToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("valoresDasPizzasToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
